Distribuidora/Distribuidora/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path,include
from core import views as core_views
from portafolio import views as portafolio_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #--------------------------------------------------------------
    path('', core_views.home, name='inicio'),
    path('acerca/', core_views.about, name='acerca'),
    path('contacto/',include ('contacto.urls')),
    path('producto/', core_views.product, name='producto'),
    path('car/', core_views.car, name='car'),

    #--------------------------------------------------------------
    path('portafolio/', portafolio_views.portafolio, name='portafolio'),
    path('carro/', include('carro.urls')),
    path('pedidos/',include('pedidos.urls')),

    #--------------------------------------------------------------
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    
    #------------------------ recuperación contraseñas --------------------------------------
    path('cambiar-contraseña/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('cambiar-contraseña/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('restablecer-contraseña/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('restablecer-contraseña/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('restablecer-contraseña/confirmar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('restablecer-contraseña/completar/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

Distribuidora/carro/urls.py
from django.urls import path

from .import views

app_name="carro"


urlpatterns = [

    path("agregar/<int:productos_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:productos_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:productos_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),

]

Distribuidora/carro/models.py
from django.db import models

# Create your models here.

Distribuidora/portafolio/models.py
from django.db import models

# Create your models here.

class category(models.Model):
    nombre = models.CharField(max_length=100)
    creado = models.DateTimeField(auto_now_add = True)
    actualizado = models.DateTimeField(auto_now = True )

    class Meta:
        verbose_name = " Categoria "
        verbose_name_plural = "Categorias"
        ordering = ['-creado']

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre_producto = models.CharField (max_length=70)
    precio = models.FloatField()
    descripcion = models.TextField ()
    imagen = models.ImageField (upload_to='projects')
    link=models.URLField (null=True,blank=True)
    categories = models.ManyToManyField(category, related_name="get_posts")
    creado = models.DateTimeField (auto_now_add=True) # añade la fecha automaticamente
    actualizado = models.DateTimeField (auto_now=True) # actualiza la fecha automaticamente

    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'
        ordering = ['-creado'] #sirve para ordenar del nuevo al antiguo

    def __str__(self): #cambiar el nombre del proyecto
        return self.nombre_producto
    

Distribuidora/carro/views.py
from django.shortcuts import render

from .carro import Carro

from portafolio.models import Producto

from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, productos_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=productos_id)

    carro.agregar(productos=producto)

    return redirect("car")

def eliminar_producto(request, productos_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=productos_id)

    carro.eliminar(productos=producto)

    return redirect("car")

def restar_producto(request, productos_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=productos_id)

    carro.restar_producto(productos=producto)

    return redirect("car")

def limpiar_carro(request):

    carro = Carro(request)

    carro.limpiar_carro()

    return redirect("car")

Distribuidora/portafolio/views.py
from django.shortcuts import render
from .models import Producto
from core.models import links

# Create your views here.

def portafolio(request):
    projects=Producto.objects.all()
    link=links.objects.all()
    return render (request, "portafolio/portafolio.html",{'projects':projects,'link':link})

Distribuidora/portafolio/templates/carro/widget.html
<div id="contenedor">
    <div class="container" id="table-car">
    
            <table class="table table-bordered" style="color: black; font-weight: bold; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); border: 2px solid #333;">

                <thead>
                    <tr>

                        <th colspan="5" class="text-center" >

                            Carro Compras
                        
                        </th>
                    
                    </tr>

                    <tr>

                        <th>Producto</th>
                        <th>Imagen</th>
                        <th>Cantidad</th>
                        <th>Acciones</th>
                        <th>Quitar</th>
                    
                    </tr>

                <thead>

                <tbody>
                    {% if request.session.carro.items %}
                        {% for key, value in request.session.carro.items %}

                            <tr class="text-center">

                                <td>{{value.nombre}}</td>
                                <td><img src="{{value.imagen}}" alt="" width="75px" height="40px"></td>
                                <td>{{value.cantidad}}</td>
                                <td>

                                    <a href="{% url 'carro:agregar' value.productos_id %}" class="btn btn-sm btn-primary boton_sumar" id="boton_sumar"> + </a>
                                    <a href="{% url 'carro:restar' value.productos_id %}" class="btn btn-sm btn-primary boton_restar" id="boton_restar"> - </a> <br/>

                                    ${{value.precio|floatformat:0}} - COP

                                </td>

                                <td>

                                    <a href="{% url 'carro:eliminar' value.productos_id  %}" class="boton_eliminar"><i class="fa-solid fa-trash"></i>
                                </td>

                            </tr>

                        {% endfor %}
                            <tr>
                                <td colspan="5">

                                    <a href="{% url 'carro:limpiar' %}"  class="btn btn-danger">Vaciar Carro</a>

                                        <!--<form action="{% url 'carro:limpiar' %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="boton-vaciar">Vaciar carrito</button>
                                        </form>-->
                                    
                                </td>
                            </tr>
                        <tfoot>
                            <td colspan="5" class="subtotal-title">TOTAL:${{importe_total_carro|floatformat:0}} - COP</td>

                                <tr>
                                    <td colspan="5" style="text-align: center;">
                                        <a href="../pedidos"  class="btn btn-primary">Comprar</a>
                                    </td>
                                </tr>
                            
                        </tfoot>

                    {% else %}
                        <tr>
                            <td colspan="5">
                                <div class="alert alert-danger text-center">

                                    Sin Productos
                                
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                </tbody>



            <!--<tfoot>
                    <tr>
                        <td colspan="3">

                            Total: {{importe_total_carro}} $-COP

                        </td>
                    </tr>
                </tfoot>-->

            </table>
    </div>
</div>

            <style>
                #contenedor {
                width: 70%; /* Ancho del contenedor al 50% de la ventana */
                margin-top: 30px;
                margin-bottom: 30px;
                margin-left: 200px;
                padding: 20px;
                border: 1px solid white; /* Contorno limpio */
                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.4); /* Sombra suave */
                text-align: center;
                transition: box-shadow 0.3s; /* Transición para el efecto hover */
                }
        
                #contenedor:hover {
                    box-shadow: 0 12px 20px rgba(0, 0, 0, 0.6); /* Más sombra en hover */
                }

                @media (max-width: 767px) {
                    #contenedor {
                       width: 90%;
                       margin-left: 18px;
                       padding: 0;
                    }
              
                    /* Hacer la tabla responsive */
                    #table-car {
                       overflow-x: auto;
                    }
              
                    .table {
                       width: 100%;
                       margin-bottom: 0;
                       font-size: 8px;
                    }
              
                    .table th,
                    .table td {
                       white-space: nowrap;
                    }
                 }

            </style>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
            $(document).ready(function() {
                // Maneja el clic en el botón de sumar
                $(document).on("click", ".boton_sumar", function(event) {
                    event.preventDefault();
                    var url = $(this).attr("href");
                
                    // Realiza una solicitud AJAX GET a la URL
                    $.get(url, function(data) {
                    // Actualiza solo la parte de la tabla del carrito
                    $("#table-car").html($(data).find("#table-car").html());
                    });
                });

                // Maneja el clic en el botón de restar (puedes hacer lo mismo para eliminar)
                $(document).on("click", ".boton_restar", function(event) {
                    event.preventDefault();
                    var url = $(this).attr("href");
                
                    // Realiza una solicitud AJAX GET a la URL
                    $.get(url, function(data) {
                    // Actualiza solo la parte de la tabla del carrito
                    $("#table-car").html($(data).find("#table-car").html());
                    });
                });

                
                // Maneja el clic en el botón de sumar
                $(document).on("click", ".boton_eliminar", function(event) {
                    event.preventDefault();
                    var url = $(this).attr("href");
                
                // Muestra un alert de confirmación
                var confirmar = confirm("¿Realmente deseas eliminar?");

                // Si el usuario hace clic en "Sí", realiza la solicitud AJAX GET
                if (confirmar) {
                    $.get(url, function(data) {
                        // Actualiza solo la parte de la tabla del carrito
                        $("#table-car").html($(data).find("#table-car").html());
                    });
                }
                });
            });
        </script>